
notARepository: 'skip'
gui:
  showFileTree: false
  showIcons: true
  authorColors:
    'Espen Strømland': 'yellow'
    '*': 'blue'
  theme:
    activeBorderColor:
      - white
      - bold
    selectedLineBgColor:
      - '#272932'
    inactiveBorderColor:
      - default
    optionsTextColor:
      - default

