
notARepository: 'skip'
gui:
  mouseEvents: false
  showFileTree: false
  theme:
    activeBorderColor:
      - white
      - bold
    selectedLineBgColor: 
      - '#282A33'
    inactiveBorderColor:
      - default
    optionsTextColor:
      - default
